version: "3"

services:
  scylla:
    image: scylladb/scylla
    container_name: database
    ports:
      - 9042:9042

  minio:
    container_name: storage
    image: minio/minio:latest
    volumes:
      - minio-data:/data # Mount a local directory for storing object data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} # Set access key
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # Set secret key
    ports:
      - "9000:9000" # Map container port 9000 to host port 9000 (for S3 API access)
      - "9001:9001" # Map container port 9001 to host port 9001 (for Minio console access)
    command: "server /data --console-address :9001"
    restart: always

  # # Scylla Monitoring Stack

  # # AlertManager
  # alertmanager:
  #   container_name: aalert
  #   image: prom/alertmanager:v0.21.0
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./prometheus/rule_config.yml:/etc/alertmanager/config.yml

  # # Grafana
  # grafana:
  #   container_name: agraf
  #   environment:
  #     - GF_PANELS_DISABLE_SANITIZE_HTML=true
  #     - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
  #     - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=scylladb-scylla-datasource
  #     # This is where you set Grafana security
  #     - GF_AUTH_BASIC_ENABLED=false
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   image: grafana/grafana:7.3.5
  #   ports:
  #     - 3000:3000
  #   user: 1000:1000
  #   volumes:
  #     # Uncomment the following line for grafana persistency
  #     # - path/to/grafana/dir:/var/lib/grafana
  #     - ./grafana/build:/var/lib/grafana/dashboards
  #     - ./grafana/plugins:/var/lib/grafana/plugins
  #     - ./grafana/provisioning:/var/lib/grafana/provisioning

  # # LOKI
  # loki:
  #   command:
  #     - --config.file=/mnt/config/loki-config.yaml
  #   container_name: loki
  #   image: grafana/loki:2.0.0
  #   ports:
  #     - 3100:3100
  #   volumes:
  #     - ./loki/rules:/etc/loki/rules
  #     - ./loki/conf:/mnt/config

  # # Prometheus
  # promotheus:
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.compose.yml
  #   container_name: aprom
  #   image: prom/prometheus:v2.18.1
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - ./prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
  #     - ./prometheus/scylla_servers.yml:/etc/scylla.d/prometheus/scylla_servers.yml
  #     - ./prometheus/scylla_manager_servers.yml:/etc/scylla.d/prometheus/scylla_manager_servers.yml
  #     - ./prometheus/scylla_servers.yml:/etc/scylla.d/prometheus/node_exporter_servers.yml
  #     # Uncomment the following line for prometheus persistency
  #     # - path/to/data/dir:/prometheus/data
  # promtail:
  #   command:
  #     - --config.file=/etc/promtail/config.yml
  #   container_name: promtail
  #   image: grafana/promtail:2.0.0
  #   ports:
  #     - 1514:1514
  #     - 9080:9080
  #   volumes:
  #     - ./loki/promtail:/etc/promtail

volumes:
  minio-data:
